
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT   = 587
SMTP_USER   = "grantsmithdev@gmail.com"
SMTP_PASS   = "vajb akxu tlvi mveg"
AIRTABLE_TOKEN = "pat6MRHBPUXfjG1dg.096c6d98af12fae41a3e5736b2ea8946d69b0bfdd53b430e2e2aff9f6145f162"
BASE_ID = "app6DojqHx8o9ULRx"
TABLE_NAME = "Menu Items"